### PR TITLE
Upgrade Android toolchain

### PR DESCRIPTION
**Pull request by shyfire131**
Should buy android devs some time. Still want to investigate upgrading to Gradle 8.

Some notable upgrades:

- latest version of react
- latest version of react-native 
- latest version of react-native-v8 with -nointl
- latest version of Kotlin
- Gradle on the latest 7.x release

Only tested on Pixel 7 up to seeing the order book, so needs more testing.

The diff of these files is the best place to see what was upgraded:

- package.json
- android/gradle/wrapper/gradle-wrapper.properties
- android/gradle.properties
- android/build.gradle
- android/app/build.gradle

Generally things seem to work though :)

TODO:

- [ ] This was all done on an M1 mac, need to test on x86 ubuntu
- [ ] Needs more testing of APKs especially areas of the app that use native plugins

## Checklist before merging
- [X] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Hey @shyfire131 , awesome that you are tackling this one. I tried a couple of times in the past and this task ended up giving me nightmares :D

When running `npx react-native run-android` locally I get:
```error
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:10: error: package com.facebook.flipper.android does not exist
import com.facebook.flipper.android.AndroidFlipperClient;
                                   ^
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:11: error: package com.facebook.flipper.android.utils does not exist
import com.facebook.flipper.android.utils.FlipperUtils;
                                         ^
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:12: error: package com.facebook.flipper.core does not exist
import com.facebook.flipper.core.FlipperClient;
                                ^
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:13: error: package com.facebook.flipper.plugins.crashreporter does not exist
import com.facebook.flipper.plugins.crashreporter.CrashReporterPlugin;
                                                 ^
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:14: error: package com.facebook.flipper.plugins.databases does not exist
import com.facebook.flipper.plugins.databases.DatabasesFlipperPlugin;
                                             ^
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:15: error: package com.facebook.flipper.plugins.fresco does not exist
import com.facebook.flipper.plugins.fresco.FrescoFlipperPlugin;
                                          ^
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:16: error: package com.facebook.flipper.plugins.inspector does not exist
import com.facebook.flipper.plugins.inspector.DescriptorMapping;
                                             ^
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:17: error: package com.facebook.flipper.plugins.inspector does not exist
import com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin;
                                             ^
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:18: error: package com.facebook.flipper.plugins.network does not exist
import com.facebook.flipper.plugins.network.FlipperOkhttpInterceptor;
                                           ^
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:19: error: package com.facebook.flipper.plugins.network does not exist
import com.facebook.flipper.plugins.network.NetworkFlipperPlugin;
                                           ^
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:20: error: package com.facebook.flipper.plugins.sharedpreferences does not exist
import com.facebook.flipper.plugins.sharedpreferences.SharedPreferencesFlipperPlugin;
                                                     ^
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:33: error: cannot find symbol
    if (FlipperUtils.shouldEnableFlipper(context)) {
        ^
  symbol:   variable FlipperUtils
  location: class ReactNativeFlipper
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:34: error: cannot find symbol
      final FlipperClient client = AndroidFlipperClient.getInstance(context);
            ^
  symbol:   class FlipperClient
  location: class ReactNativeFlipper
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:34: error: cannot find symbol
      final FlipperClient client = AndroidFlipperClient.getInstance(context);
                                   ^
  symbol:   variable AndroidFlipperClient
  location: class ReactNativeFlipper
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:36: error: cannot find symbol
      client.addPlugin(new InspectorFlipperPlugin(context, DescriptorMapping.withDefaults()));
                           ^
  symbol:   class InspectorFlipperPlugin
  location: class ReactNativeFlipper
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:36: error: cannot find symbol
      client.addPlugin(new InspectorFlipperPlugin(context, DescriptorMapping.withDefaults()));
                                                           ^
  symbol:   variable DescriptorMapping
  location: class ReactNativeFlipper
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:37: error: cannot find symbol
      client.addPlugin(new DatabasesFlipperPlugin(context));
                           ^
  symbol:   class DatabasesFlipperPlugin
  location: class ReactNativeFlipper
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:38: error: cannot find symbol
      client.addPlugin(new SharedPreferencesFlipperPlugin(context));
                           ^
  symbol:   class SharedPreferencesFlipperPlugin
  location: class ReactNativeFlipper
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:39: error: cannot find symbol
      client.addPlugin(CrashReporterPlugin.getInstance());
                       ^
  symbol:   variable CrashReporterPlugin
  location: class ReactNativeFlipper
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:41: error: cannot find symbol
      NetworkFlipperPlugin networkFlipperPlugin = new NetworkFlipperPlugin();
      ^
  symbol:   class NetworkFlipperPlugin
  location: class ReactNativeFlipper
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:41: error: cannot find symbol
      NetworkFlipperPlugin networkFlipperPlugin = new NetworkFlipperPlugin();
                                                      ^
  symbol:   class NetworkFlipperPlugin
  location: class ReactNativeFlipper
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:46: error: cannot find symbol
              builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
                                                ^
  symbol: class FlipperOkhttpInterceptor
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:65: error: cannot find symbol
                        client.addPlugin(new FrescoFlipperPlugin());
                                             ^
  symbol: class FrescoFlipperPlugin
/home/user/robosats/mobile/android/app/src/debug/java/com/robosats/ReactNativeFlipper.java:71: error: cannot find symbol
        client.addPlugin(new FrescoFlipperPlugin());
                             ^
  symbol:   class FrescoFlipperPlugin
  location: class ReactNativeFlipper
24 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 11s
```

When running `./gradlew assembleRelease`, we get this other error. It happens both, locally and on our release workflow (here full GH Action logs https://github.com/RoboSats/robosats/actions/runs/5056095489/jobs/9073141503)
```
> Task :react-native-v8:buildCMakeRelWithDebInfo[arm64-v8a][v8executor]
C/C++: ninja: Entering directory `/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/android/.cxx/RelWithDebInfo/5iv263h6/arm64-v8a'
C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)

> Task :react-native-v8:buildCMakeRelWithDebInfo[arm64-v8a][v8executor] FAILED
91 actionable tasks: 91 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-v8:buildCMakeRelWithDebInfo[arm64-v8a][v8executor]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/android/.cxx/RelWithDebInfo/5iv263h6/arm64-v8a'
  [1/14] Building CXX object CMakeFiles/reactnative_internal_static.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native/ReactCommon/reactperflogger/reactperflogger/BridgeNativeModulePerfLogger.cpp.o
  [2/14] Building CXX object CMakeFiles/reactnative_internal_static.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native/ReactCommon/cxxreact/JSExecutor.cpp.o
  [3/14] Building CXX object CMakeFiles/reactnative_internal_static.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native/ReactCommon/jsiexecutor/jsireact/JSINativeModules.cpp.o
  [4/14] Building CXX object CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/JSIV8ValueConverter.cpp.o
  [5/14] Building CXX object CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/HostProxy.cpp.o
  [6/14] Building CXX object CMakeFiles/reactnative_internal_static.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native/ReactCommon/jsiexecutor/jsireact/JSIExecutor.cpp.o
  [7/14] Linking CXX static library libreactnative_internal_static.a
  [8/14] Building CXX object CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/V8PointerValue.cpp.o
  [9/14] Building CXX object CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/V8RuntimeFactory.cpp.o
  [10/14] Building CXX object CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/V8Runtime.cpp.o
  [11/14] Building CXX object CMakeFiles/v8executor.dir/src/main/cpp/V8ExecutorFactory.cpp.o
  [12/14] Building CXX object CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/V8Inspector.cpp.o
  [13/14] Building CXX object CMakeFiles/v8executor.dir/src/main/cpp/OnLoad.cpp.o
  [14/14] Linking CXX shared library ../../../../build/intermediates/cxx/RelWithDebInfo/5iv263h6/obj/arm64-v8a/libv8executor.so
  FAILED: ../../../../build/intermediates/cxx/RelWithDebInfo/5iv263h6/obj/arm64-v8a/libv8executor.so 
  : && /usr/local/lib/android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android26 --gcc-toolchain=/usr/local/lib/android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/usr/local/lib/android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -DREACT_NATIVE_TARGET_VERSION=71 -fexceptions -fno-omit-frame-pointer -frtti -Wno-sign-compare -fstack-protector-all -DV8_COMPRESS_POINTERS -O2 -g -DNDEBUG  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libv8executor.so -o ../../../../build/intermediates/cxx/RelWithDebInfo/5iv263h6/obj/arm64-v8a/libv8executor.so CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/HostProxy.cpp.o CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/JSIV8ValueConverter.cpp.o CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/V8Inspector.cpp.o CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/V8PointerValue.cpp.o CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/V8Runtime.cpp.o CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/V8RuntimeFactory.cpp.o CMakeFiles/v8executor.dir/src/main/cpp/V8ExecutorFactory.cpp.o CMakeFiles/v8executor.dir/src/main/cpp/OnLoad.cpp.o  /usr/local/lib/android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/26/liblog.so  -landroid  /home/runner/.gradle/caches/transforms-3/5d07f50a3418bed82ae08cf2148d9eae/transformed/jetified-fbjni-0.3.0/prefab/modules/fbjni/libs/android.arm64-v8a/libfbjni.so  /home/runner/.gradle/caches/transforms-3/b03bb67f791cdea275f2788aac865b2e/transformed/jetified-react-android-0.71.8-release/prefab/modules/jsinspector/libs/android.arm64-v8a/libjsinspector.so  /home/runner/.gradle/caches/transforms-3/b03bb67f791cdea275f2788aac865b2e/transformed/jetified-react-android-0.71.8-release/prefab/modules/runtimeexecutor/libs/android.arm64-v8a/libruntimeexecutor.so  libreactnative_internal_static.a  ../../../../build/jniLibs/v8/jni/arm64-v8a/libv8android.so  /home/runner/.gradle/caches/transforms-3/b03bb67f791cdea275f2788aac865b2e/transformed/jetified-react-android-0.71.8-release/prefab/modules/folly_runtime/libs/android.arm64-v8a/libfolly_runtime.so  /home/runner/.gradle/caches/transforms-3/b03bb67f791cdea275f2788aac865b2e/transformed/jetified-react-android-0.71.8-release/prefab/modules/glog/libs/android.arm64-v8a/libglog.so  /home/runner/.gradle/caches/transforms-3/b03bb67f791cdea275f2788aac865b2e/transformed/jetified-react-android-0.71.8-release/prefab/modules/jsi/libs/android.arm64-v8a/libjsi.so  /home/runner/.gradle/caches/transforms-3/b03bb67f791cdea275f2788aac865b2e/transformed/jetified-react-android-0.71.8-release/prefab/modules/reactnativejni/libs/android.arm64-v8a/libreactnativejni.so  -latomic -lm && :
  CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/V8Runtime.cpp.o: In function `std::__ndk1::__fs::filesystem::path::filename() const':
  /usr/local/lib/android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/filesystem:1067: undefined reference to `std::__ndk1::__fs::filesystem::path::__filename() const'
  CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/V8Runtime.cpp.o: In function `std::__ndk1::__fs::filesystem::path::has_root_directory() const':
  /usr/local/lib/android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/filesystem:1084: undefined reference to `std::__ndk1::__fs::filesystem::path::__root_directory() const'
  CMakeFiles/v8executor.dir/home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/src/v8runtime/V8Runtime.cpp.o: In function `std::__ndk1::__fs::filesystem::path::has_filename() const':
  /usr/local/lib/android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/filesystem:1096: undefined reference to `std::__ndk1::__fs::filesystem::path::__filename() const'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
  
  C++ build system [build] failed while executing:
      /usr/local/lib/android/sdk/cmake/3.18.1/bin/ninja \
        -C \
        /home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/android/.cxx/RelWithDebInfo/5iv263h6/arm64-v8a \
        v8executor
    from /home/runner/work/robosats/robosats/mobile/node_modules/react-native-v8/android
```

I cleared the cache of our android release workflow and retried, but it got the same error (cleaned everything too locally).

**Comment by Reckless-Satoshi** [comment]
Okay. I do not often quote Elon Musk but this is an exceptional case: "the best part, is no part". I removed `react-native-v8` and `v8-android-nointl` . As far as I can tell, the app is fully functional without the dependencies. See branch https://github.com/RoboSats/robosats/compare/main...update-android-toolchain

Which leads question why these dependencies were needed in the first place :smile:  . I believe `react-native-tor` could not work on react-native v0.69 without them, but this is just a blurry memory of a conversation with @KoalaSat (only I could find this as context https://github.com/RoboSats/robosats/pull/247)

Find build artifacts on pre-release: https://github.com/RoboSats/robosats/releases/tag/android-66eb18c

**Comment by shyfire131** [comment]
I checked out this branch locally and can confirm that removing v8 works on my side too. Although I think there is still a stale maven repository reference for it but I'll omit that when I update this branch.

Going to try bumping Gradle to Gradle 8 now.

**Comment by shyfire131** [comment]
Very nice! Just to be clear, the null hypothesis for your p-values is "Removing V8 would slow down performance" ?

**Comment by Reckless-Satoshi** [comment]
> the null hypothesis for your p-values is "Removing V8 would slow down performance"

Given that is a two-sided t-test, the null hypothesis is "Removing V8 has no performance impact". A small p-value, like we got, means that, indeed, it has performance impact. However, the impact seems to be for increased performance with no V8. Most likely V8 has no impact and the increase performance must be some optimizations of react-native v0.71.8. But that's enough of nerding around! :D

**Comment by Reckless-Satoshi** [comment]
Merged into main via another branch without the dependaBot merge conflicts. 

Thank you @shyfire131  taking a look and getting this to work on the newer react-native. Please accept a 200K Sats donation from the devfund. Send an invoice from a proxy wallets with a >24h expiration time :D

**Comment by shyfire131** [comment]
lnbc2m1pj8vt9app5g77zcsphuzd8v0dlvqnmydaevgjflzfsz8agsgfjvu4ye2dtl2zqdqu2askcmr9wssx7e3q2dshgmmndp5scqzzsxqyz5vqsp5p76lkcy38564kypyk3gs47wxd8vvsjvugv2r5g0uvvzdqa7n9mes9qyyssqqpgtfyjtaqqs477r40dyvj2rj0ywlr9zx0hmljvkhatuahlyk4vjkv5hy0e0pad7txp89vnatdrnxl8z9gvehvvyfq8xpatdrcxu9cgpwwt9v6
